### ISSUE TITLE
Is this actually using the instruct version of Falcon?

### ISSUE THREAD

**Issue by kmulka-bloomberg** [marshmellow77/falcon-document-chatbot#2]
Does it matter that this model is falcon-40b and not falcon-40b-instruct?
https://github.com/marshmellow77/falcon-document-chatbot/blob/main/chatbot.py#LL17C1-L17C6

**Comment by heiko-hotz** [comment]
Hi @kmulka-bloomberg, in this Python scrip I'm using only the tokenizer to count the number of tokens in the memory (i.e. it doesn't load the actual model). For the tokenizer it doesn't matter which model (instruct or not) is being used :) 

See here for the code where the tokenizer is being used: https://github.com/marshmellow77/falcon-document-chatbot/blob/main/chatbot.py#L105
